#%RAML 1.0 Trait

headers:
  client_id:
    description: Client Id
    type: string
    required: true
    example: "kjfgj1234kkfhggjjnjjkkk"
  client_secret:
    description: Client Secret
    type: string
    required: true
    example: "kjfgj1234kkfhggjjnjjkkk"
